### ISSUE TITLE
Using Sublime 3 to compile TypeScript gives me an error about Temporary ASP.NET Files directory already exists

### ISSUE THREAD

**Issue by Mule52** [Phaiax/ArcticTypescript#22]
Before I begin, thanks for ArcticTypescript! I allows me to work efficiently in Sublime 3 with TypeScript.

Now my issue.

My main application is running via Visual Studio 2013, Windows 8.1 ASP.NET 4.5. I launch my VS web application in debug mode. I am trying to use Sublime as my editor for TypeScript (TS files) and LESS files. I have the package ArcticTypeScript installed in Sublime 3. I believe it compiles TS correctly, EXCEPT for the following error.

ERRORS :
A subdirectory or file C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files already exists.

When I compile TS files, this error just shows up in the build console of Sublime. I can still work, but why is this error happening? This "error" is driving me crazy.

Any ideas why this is happening?

Would this have anything to do with Browserlink running in VisualStudio? Is it possible for me to run some cmd file before the compiles to delete that temporary directory?

Thanks for any help!

**Comment by Phaiax** [comment]
Hey Mule52

This is the strerr stream output of tsc (tsc: the typescript compiler).

You can execute tsc in a commandline (with the same parameters), and the same message should appear.

You may only need to adjust some parameters.

If you notice, that this message is caused by missing ```"```, then please report back.

Otherwise I would guess it's something related to your specific project, because it's a compiler error.

**Comment by Mule52** [comment]
I ran into similar "Temporary ASP.NET Files already exists" issues with visual studio. Long story short, I repaved my computer. I have not seen these issues since, so you can close this issue. Thanks for the help.
