### ISSUE TITLE
Stuck on loading screen (Typescript project is initializing [  =  ])

### ISSUE THREAD

**Issue by lucasmciruzzi** [Phaiax/ArcticTypescript#39]
I get stuck in the initial loading screen and I get this error on console:

    Exception in thread Thread-[Some Number]
        File "./subprocess.py", line 1112, in _execute_child
    PremissionError: [WinError 5] Access is denied

I'm running ST3 in Windows 8.1. I tested with Python 2.7 and 3.4, witno node and io.js, and all behave the same way. I tried with a new project, and it gets the same result.

![example](https://cloud.githubusercontent.com/assets/3979433/6765407/e8f31216-cfbd-11e4-8969-75f8e5ba575a.jpg)

**Comment by lucasmciruzzi** [comment]
It was working until a few days ago, I guess this bugs is related with the recent updates.

**Comment by Phaiax** [comment]
I have seen it and I'll take a look soon  ... I think I have fixed it for mac and broke it for windows... damn :D

**Comment by lucasmciruzzi** [comment]
hahahaha ... no problem, if I had any idea of how to code in python, I would try to fix it myself. This is, by far, the best package for Sublime Text, so the wait is worth.

**Comment by Phaiax** [comment]
Hm, I can't figure out why exactly this is happening.

The change I did a few days ago, was to fix a bug that otherwise ignored settings made in the general user settings files. Maybe you have set your `node_path` somewhere, and now it is no longer ignored.

AT (with version 0.6.4, it'll take 1-2 hours after it will automatically be upgraded with your next sublime restart) will now catch that exception and will print out the exact command that failed to execute and that has raised the PermissionError. Maybe the exact message will help you. If not, just c'n'p the error into this issue.

**Comment by lucasmciruzzi** [comment]
Fixed, I had the directory of node instead of the node executable in the node_path. That new error message is great: Informative and it avoids getting stuck in the "Typescript project is initializing" message.

Thanks!
